[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/logo.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "/app.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"
